# Generated by Django 3.1.7 on 2021-03-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
